services:
    nginx:
        container_name: ${CONTAINER_NAME}-nginx
        image: nginx:1.27.0-alpine
        restart: unless-stopped
        env_file: .env
        ports:
            - ${CONTAINER_PORT}:80
        volumes:
            - ./nginx:/etc/nginx/conf.d:rw
            - wordpress:/var/www/html:rw
        networks:
            - internal

    database:
        container_name: ${CONTAINER_NAME}-database
        image: mysql:9.0
        restart: unless-stopped
        env_file: .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USER}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        healthcheck:
            test:
                [
                    "CMD",
                    "mysqladmin",
                    "ping",
                    "-h",
                    "127.0.0.1",
                    "-u",
                    "root",
                    "-p${DATABASE_PASSWORD}",
                ]
            timeout: 20s
            retries: 10
        ports:
            - ${DATABASE_PORT}:3306
        volumes:
            - db-data:/var/lib/mysql
        networks:
            - internal

    phpmyadmin:
        container_name: ${CONTAINER_NAME}-phpmyadmin
        image: phpmyadmin/phpmyadmin
        restart: unless-stopped
        env_file: .env
        environment:
            PMA_HOST: database # use the same name as database service
            PMA_PORT: ${DATABASE_PORT}
            MYSQL_ROOT_PASSWORD: "${DATABASE_ROOT_PASSWORD}"
        ports:
            - ${PHP_MY_ADMIN_PORT}:80
        depends_on:
            - database
        networks:
            - internal

    wordpress:
        depends_on:
            - database
        container_name: ${CONTAINER_NAME}-wordpress
        image: wordpress:6.5.5-fpm-alpine
        restart: unless-stopped
        env_file: .env
        environment:
            WORDPRESS_DB_HOST: database:3306 # use the same name as database service
            WORDPRESS_DB_NAME: "${DATABASE_NAME}"
            WORDPRESS_DB_USER: "${DATABASE_USER}"
            WORDPRESS_DB_PASSWORD: "${DATABASE_PASSWORD}"
            PUID: 82 # Set this to the host UID
            PGID: 82 # Set this to the host GID
        volumes:
            - wordpress:/var/www/html
            - ./src:/var/www/html/wp-content:rw
        networks:
            - internal

volumes:
    db-data:
    wordpress:

networks:
    internal:
        driver: bridge
